### PR TITLE
Use monospace font in custom command output.

### PR DESCRIPTION
**Pull request by tvoverbeek**
Fixed Storage output to list all partitions and corrected percentage
calculation.

### CODE REVIEW

**Comment by tvoverbeek** [comment]
Lorenzo,

You changed the start of the for loop in the Storage computation back to 1.
When the loop index starts at 1 it only shows my /boot partition and skips my / partition (the much larger ext4 one).
Why do you skip the first entry in lines?
My SD card uses the 'pure' Raspbian image, not NOOBS.
I know NOOBS uses a different partition scheme.
If you want to cover both NOOBS and non-NOOBS we need some better intelligence in the loop.

Ton

**Comment by LorenzoRogai** [comment]
I skipped the first line because "df -T" command output the following

```
$ df -T
Filesystem    Type   1K-blocks      Used Available Use% Mounted on
....
```

If i start the loop from 0 it gives a exception

I also use raspbian

**Comment by tvoverbeek** [comment]
I know about the header line of "df -T" output, but you remove this line
with the following grep command:
'df -T | grep -vE "tmpfs|rootfs|Filesystem"', so it never gets in the lines
array.

## Here is my 'df -T' output:

Filesystem     Type     1K-blocks    Used Available Use% Mounted on
rootfs         rootfs    30616076 4372356  24981280  15% /
/dev/root      ext4      30616076 4372356  24981280  15% /
devtmpfs       devtmpfs    183572       0    183572   0% /dev
tmpfs          tmpfs        38368     252     38116   1% /run
tmpfs          tmpfs         5120       0      5120   0% /run/lock
tmpfs          tmpfs        76720       0     76720   0% /run/shm

## /dev/mmcblk0p1 vfat         57288   28880     28408  51% /boot

With the grep command only the ext4 and vfat partitions are stored in the
lines array.
Starting the for loop with index 1 only shows the /boot vfat partition in
Storage.

Can you step through the for loop with adb (or debug in Eclipse) to see
what causes your exception?

Regards,

Ton

**Comment by LorenzoRogai** [comment]
You're right the exception happened because i use italian locale and "Filesystem" is written as "File system"

Fixed

**Comment by tvoverbeek** [comment]
Use locale dependent strings (res/values/strings.xml,
res/values-it/strings.xml, etc.) ?
Might be a good idea to have all strings localized, or at least prepared to
be localized.

Ton

**Pull request merged**
